name: Auto Assign & Label

on:
  pull_request:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Add reviewers and labels
        uses: actions-ecosystem/action-add-reviewers@v1
        with:
          reviewers: shochaso
      - name: Add labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "area/ui"

